# Jest 测试异步代码

## [测试异步代码](https://jestjs.io/docs/zh-Hans/asynchronous)
### 回调函数
默认情况下当 fetchData 执行完成的时候，Jest 的测试就完成了，不会再执行回调函数，导致测试不会按预期工作。
Jest 为解决这种情况，提供了 done 回调函数，Jest 将等到调用 done 回调函数执行后才完成测试。
```js
test('the data is peanut butter', done => {
  function callback(data) {
    expect(data).toBe('peanut butter');
    done();
  }
 
  fetchData(callback);
});
```

### Promise
从测试中返回一个 promise，那么 Jest 将等待 promise 被 resolve。如果这个 promise 被 rejected，这个测试将自动失败。
```javascript
test('the data is peanut butter', () => {
  return fetchData().then(data => {
    expect(data).toBe('peanut butter');
  });
});
```
如果你希望一个 promise 被 rejected，可以使用 .catch 方法。确保添加 expect.assertions 来验证调用了一定数量的断言。否则，一个 fulfilled promise 将不会失败。
```javascript
test('the fetch fails with an error', () => {
  expect.assertions(1);
  return fetchData().catch(e => expect(e).toMatch('error'));
});
```

### Async/Await
```javascript
test('the data is peanut butter', async () => {
  const data = await fetchData();
  expect(data).toBe('peanut butter');
});
```

### .resolves / .rejects
可以在 expect 语句中使用 .resolves 匹配器，Jest 将等待此 Promise 解决。 如果承诺被拒绝，则测试将自动失败。
```javascript
test('the data is peanut butter', () => {
  return expect(fetchData()).resolves.toBe('peanut butter');
});
```
如果你想要 Promise 被拒绝，使用 .rejects 匹配器
```javascript
test('the fetch fails with an error', () => {
  return expect(fetchData()).rejects.toMatch('error');
});
```
